
* Nome do Software (ou Biblioteca):
- DESENVOLVIMENTO DO SOFTWARE APLICAÇÃO DE CORRELAÇÕES PARA CÁLCULO DE PARÂMETROS DE RESERVATÓRIO A PARTIR DE PROPRIEDADES DOS FLUIDOS – MODELAGEM BLACKOIL

* Resumo e/ou informação extra: 
- Utilizar correlações empı́ricas para cálculo de parâmetros de um reservatório a
partir de propriedades dos fluidos presentes no mesmo – Modelagem BlackOil.
– Calcular propriedades dos fluidos a partir de dados externos.
– Calcular parâmetros de um reservatório utilizando correlações especı́ficas.

* Versão: 
- 1.0.

* Data:
- 2016/2 - segundo semestre.
  
* Autor de Contato:
- André Duarte Bueno <andreduartebueno@gmail.com>

* Lista dos Autores:
- JOÃO BOSCO MACIEL FILHO
- SUSANE CHELLI CAIRES GOIS
- André Duarte Bueno <andreduartebueno@gmail.com>

* Áreas de pesquisa vinculadas: 
- Modelagem Matemática Computacional
- Engenharia Reservatório 

* Vinculo com: 
- Trabalho da disciplina de programação prática.

* Paradigmas: 
- POO - Programação Orientada a Objeto (códigos em C++)

* Tipo de Interface: 
- Terminal e gráfica (gnuplot).

* Plataformas Suportadas: 
- Windows e GNU/Linux e Mac OS X (não testada).

* Linguagens Utilizadas: 
- C++ 11.

* Bibliotecas Utilizadas (dependências):
- CGnuplot - https://github.com/ldsc/CGnuplot

* Softwares utilizados (dependências)
- gnuplot http://www.gnuplot.info/

* Tipo de Licença:
- GPL
- Entre em contato com o Prof. André Duarte Bueno
  andreduartebueno@gmail.com
  para que o mesmo gere um novo projeto no github do ldsc para que você (e sua equipe) possam trabalhar na nova versão.
- Se este projeto tem como número de versão 1.0 a nova versão deverá ser 2.0 e assim sucessivamente.
- Os nomes dos autores originais deve ser preservada na nova versão, ou seja, adicione a informação do número da versão, os nomes dos membros da nova equipe, mas jamais apague os nomes dos autores originais (isto seria plágio).
- Na descrição do projeto informe que trata-se de uma nova versão, que tem como base a versão anterior e DESTAQUE COM CLAREZA E OBJETIVIDADE QUAIS AS NOVIDADES DA NOVA VERSÃO.
  
* Links:

